url:
  bikeUrl: http://openapi.seoul.go.kr:8088/4b64546d6862687339384d4b625366/json/
  tourUrl: http://api.visitkorea.or.kr/openapi/service/rest/KorService/
  restaurantUrl: http://openapi.seoul.go.kr:8088/4b64546d6862687339384d4b625366/json/
  leisureUrl: http://api.visitkorea.or.kr/openapi/service/rest/KorService/